<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_simpan</name>
   <tag></tag>
   <elementGuidId>32b775e0-10b5-4378-b9ab-fc116e617075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pull-right.drop-up > button.ladda-button.btn.btn-primary.std-btn-width > span.ladda-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div[3]/div/div/div/div[2]/div/div/div/div/div[3]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd61eece-c101-47bf-90e2-41e65a21bbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ladda-label</value>
      <webElementGuid>84a04a5b-e8b8-4951-9f98-f08860b90010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>656e13b0-17d0-4ee2-8ebc-8ff02a7d6a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;wrapper wrapper-content&quot;]/div[1]/div[1]/div[1]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;page-editor&quot;]/div[3]/div[@class=&quot;pull-right drop-up&quot;]/button[@class=&quot;ladda-button btn btn-primary std-btn-width&quot;]/span[@class=&quot;ladda-label&quot;]</value>
      <webElementGuid>ecc66997-b5bd-4275-8ec7-444b8b1614fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div/div/div[2]/div/div/div/div/div[3]/div/button/span</value>
      <webElementGuid>414d1012-dc88-4d46-aa76-25bd45184f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harap pilih'])[1]/following::span[12]</value>
      <webElementGuid>c00053a8-0ed7-42db-9398-cdf941e4277b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[2]/following::span[14]</value>
      <webElementGuid>fd6a7f86-0859-4c4f-a778-21da8fc68dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version number.'])[1]/preceding::span[2]</value>
      <webElementGuid>ef9a3e8d-5388-45b2-adcb-f4bf305a6678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>bd0738a2-5d5c-482b-bf6b-3a01b3960b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/span</value>
      <webElementGuid>8388d41b-2b4f-4fab-a665-a473b297a801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>733b26a2-6534-4d15-8f5d-873db7ee387d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
