<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sku</name>
   <tag></tag>
   <elementGuidId>f88bd235-c787-4e4f-9541-2f7365879228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.selectivity-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2950337f-74b5-492c-b8ed-effdc305cb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d00ad1d-6015-43eb-8ec2-abf47db536e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectivity-search-input</value>
      <webElementGuid>d68f04f1-2f65-4ea4-a4e4-38a853b98937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/div[8]/div[@class=&quot;rdg-editor-container&quot;]/div[@class=&quot;selectivity-input editor-main open&quot;]/div[@class=&quot;selectivity-dropdown has-search-input&quot;]/div[@class=&quot;selectivity-search-input-container&quot;]/input[@class=&quot;selectivity-search-input&quot;]</value>
      <webElementGuid>3057dc0d-5dd9-4d7c-bb2c-b958fdae6d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>649f0865-6b64-4c83-9bcc-0d5cabd809b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-top']/div[8]/div/div/div[2]/div/input</value>
      <webElementGuid>7255b0f6-2c9a-42f8-9d9f-20b2f16efcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/input</value>
      <webElementGuid>3c8a34b4-b5ec-44bb-9241-6f2ac8e9d512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>d82799f5-8545-453b-937b-d0885fb94ae9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
