<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_akun</name>
   <tag></tag>
   <elementGuidId>7e11e5eb-c027-4a12-984b-dd419e538449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_menu > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='user_menu']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a28f100-4953-436e-9690-dacb3b6b78d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>qa.rakamin.jubelio@gmail.com</value>
      <webElementGuid>16184c08-b2d7-459d-97c3-91e8c5f9d8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_menu&quot;)/span[1]</value>
      <webElementGuid>b9bbe4ab-7994-45cb-9822-e39da6589609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='user_menu']/span</value>
      <webElementGuid>342852f3-c5f4-4479-9dac-dec02860687a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bantuan'])[1]/following::span[1]</value>
      <webElementGuid>55fd75c3-3eb5-4d3a-8d53-9550104c574a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Toko Online Gratis'])[1]/following::span[2]</value>
      <webElementGuid>1175d406-fc3a-4e8f-a59d-28799a28fc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persediaan'])[3]/preceding::span[2]</value>
      <webElementGuid>d2be0663-9499-4576-810e-8352084557b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persediaan'])[4]/preceding::span[2]</value>
      <webElementGuid>ba0917e7-1239-4d46-803c-68e25191ebae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='qa.rakamin.jubelio@gmail.com']/parent::*</value>
      <webElementGuid>bce720a1-126e-44d8-a052-97926f91a3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/a/span</value>
      <webElementGuid>0b6fec14-e471-482a-9bd0-6bff52ba4227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'qa.rakamin.jubelio@gmail.com' or . = 'qa.rakamin.jubelio@gmail.com')]</value>
      <webElementGuid>efe7d7cc-cb5e-4bac-be39-16ca8357d998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
